/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Merge.CRMClient.Client;
using Merge.CRMClient.Api;
// uncomment below to import models
//using Merge.CRMClient.Model;

namespace Merge.CRMClient.Test.Api
{
    /// <summary>
    ///  Class for testing AccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AccountsApiTests : IDisposable
    {
        private AccountsApi instance;

        public AccountsApiTests()
        {
            instance = new AccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AccountsApi
            //Assert.IsType<AccountsApi>(instance);
        }

        /// <summary>
        /// Test AccountsCreate
        /// </summary>
        [Fact]
        public void AccountsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //CRMAccountEndpointRequest cRMAccountEndpointRequest = null;
            //bool? isDebugMode = null;
            //bool? runAsync = null;
            //var response = instance.AccountsCreate(xAccountToken, cRMAccountEndpointRequest, isDebugMode, runAsync);
            //Assert.IsType<CRMAccountResponse>(response);
        }

        /// <summary>
        /// Test AccountsList
        /// </summary>
        [Fact]
        public void AccountsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //DateTime? createdAfter = null;
            //DateTime? createdBefore = null;
            //string cursor = null;
            //bool? includeDeletedData = null;
            //bool? includeRemoteData = null;
            //bool? includeRemoteFields = null;
            //DateTime? modifiedAfter = null;
            //DateTime? modifiedBefore = null;
            //string ownerId = null;
            //int? pageSize = null;
            //string remoteId = null;
            //var response = instance.AccountsList(xAccountToken, createdAfter, createdBefore, cursor, includeDeletedData, includeRemoteData, includeRemoteFields, modifiedAfter, modifiedBefore, ownerId, pageSize, remoteId);
            //Assert.IsType<PaginatedAccountList>(response);
        }

        /// <summary>
        /// Test AccountsMetaPatchRetrieve
        /// </summary>
        [Fact]
        public void AccountsMetaPatchRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //var response = instance.AccountsMetaPatchRetrieve(xAccountToken, id);
            //Assert.IsType<MetaResponse>(response);
        }

        /// <summary>
        /// Test AccountsMetaPostRetrieve
        /// </summary>
        [Fact]
        public void AccountsMetaPostRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //var response = instance.AccountsMetaPostRetrieve(xAccountToken);
            //Assert.IsType<MetaResponse>(response);
        }

        /// <summary>
        /// Test AccountsPartialUpdate
        /// </summary>
        [Fact]
        public void AccountsPartialUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //PatchedCRMAccountEndpointRequest patchedCRMAccountEndpointRequest = null;
            //bool? isDebugMode = null;
            //bool? runAsync = null;
            //var response = instance.AccountsPartialUpdate(xAccountToken, id, patchedCRMAccountEndpointRequest, isDebugMode, runAsync);
            //Assert.IsType<CRMAccountResponse>(response);
        }

        /// <summary>
        /// Test AccountsRemoteFieldClassesList
        /// </summary>
        [Fact]
        public void AccountsRemoteFieldClassesListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //string cursor = null;
            //bool? includeDeletedData = null;
            //bool? includeRemoteData = null;
            //bool? includeRemoteFields = null;
            //int? pageSize = null;
            //var response = instance.AccountsRemoteFieldClassesList(xAccountToken, cursor, includeDeletedData, includeRemoteData, includeRemoteFields, pageSize);
            //Assert.IsType<PaginatedRemoteFieldClassList>(response);
        }

        /// <summary>
        /// Test AccountsRetrieve
        /// </summary>
        [Fact]
        public void AccountsRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //bool? includeRemoteData = null;
            //bool? includeRemoteFields = null;
            //var response = instance.AccountsRetrieve(xAccountToken, id, includeRemoteData, includeRemoteFields);
            //Assert.IsType<Account>(response);
        }
    }
}
