/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Merge.CRMClient.Client;
using Merge.CRMClient.Api;
// uncomment below to import models
//using Merge.CRMClient.Model;

namespace Merge.CRMClient.Test.Api
{
    /// <summary>
    ///  Class for testing EngagementsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class EngagementsApiTests : IDisposable
    {
        private EngagementsApi instance;

        public EngagementsApiTests()
        {
            instance = new EngagementsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EngagementsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' EngagementsApi
            //Assert.IsType<EngagementsApi>(instance);
        }

        /// <summary>
        /// Test EngagementsCreate
        /// </summary>
        [Fact]
        public void EngagementsCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //EngagementEndpointRequest engagementEndpointRequest = null;
            //bool? isDebugMode = null;
            //bool? runAsync = null;
            //var response = instance.EngagementsCreate(xAccountToken, engagementEndpointRequest, isDebugMode, runAsync);
            //Assert.IsType<EngagementResponse>(response);
        }

        /// <summary>
        /// Test EngagementsList
        /// </summary>
        [Fact]
        public void EngagementsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //DateTime? createdAfter = null;
            //DateTime? createdBefore = null;
            //string cursor = null;
            //bool? includeDeletedData = null;
            //bool? includeRemoteData = null;
            //bool? includeRemoteFields = null;
            //DateTime? modifiedAfter = null;
            //DateTime? modifiedBefore = null;
            //int? pageSize = null;
            //string remoteId = null;
            //var response = instance.EngagementsList(xAccountToken, createdAfter, createdBefore, cursor, includeDeletedData, includeRemoteData, includeRemoteFields, modifiedAfter, modifiedBefore, pageSize, remoteId);
            //Assert.IsType<PaginatedEngagementList>(response);
        }

        /// <summary>
        /// Test EngagementsMetaPatchRetrieve
        /// </summary>
        [Fact]
        public void EngagementsMetaPatchRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //var response = instance.EngagementsMetaPatchRetrieve(xAccountToken, id);
            //Assert.IsType<MetaResponse>(response);
        }

        /// <summary>
        /// Test EngagementsMetaPostRetrieve
        /// </summary>
        [Fact]
        public void EngagementsMetaPostRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //var response = instance.EngagementsMetaPostRetrieve(xAccountToken);
            //Assert.IsType<MetaResponse>(response);
        }

        /// <summary>
        /// Test EngagementsPartialUpdate
        /// </summary>
        [Fact]
        public void EngagementsPartialUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //PatchedEngagementEndpointRequest patchedEngagementEndpointRequest = null;
            //bool? isDebugMode = null;
            //bool? runAsync = null;
            //var response = instance.EngagementsPartialUpdate(xAccountToken, id, patchedEngagementEndpointRequest, isDebugMode, runAsync);
            //Assert.IsType<EngagementResponse>(response);
        }

        /// <summary>
        /// Test EngagementsRemoteFieldClassesList
        /// </summary>
        [Fact]
        public void EngagementsRemoteFieldClassesListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //string cursor = null;
            //bool? includeDeletedData = null;
            //bool? includeRemoteData = null;
            //bool? includeRemoteFields = null;
            //int? pageSize = null;
            //var response = instance.EngagementsRemoteFieldClassesList(xAccountToken, cursor, includeDeletedData, includeRemoteData, includeRemoteFields, pageSize);
            //Assert.IsType<PaginatedRemoteFieldClassList>(response);
        }

        /// <summary>
        /// Test EngagementsRetrieve
        /// </summary>
        [Fact]
        public void EngagementsRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xAccountToken = null;
            //Guid id = null;
            //bool? includeRemoteData = null;
            //bool? includeRemoteFields = null;
            //var response = instance.EngagementsRetrieve(xAccountToken, id, includeRemoteData, includeRemoteFields);
            //Assert.IsType<Engagement>(response);
        }
    }
}
