/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing AddressTypeEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressTypeEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressTypeEnum
        //private AddressTypeEnum instance;

        public AddressTypeEnumTests()
        {
            // TODO uncomment below to create an instance of AddressTypeEnum
            //instance = new AddressTypeEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressTypeEnum
        /// </summary>
        [Fact]
        public void AddressTypeEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressTypeEnum
            //Assert.IsType<AddressTypeEnum>(instance);
        }



    }

}
