/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing AddressRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AddressRequest
        //private AddressRequest instance;

        public AddressRequestTests()
        {
            // TODO uncomment below to create an instance of AddressRequest
            //instance = new AddressRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AddressRequest
        /// </summary>
        [Fact]
        public void AddressRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AddressRequest
            //Assert.IsType<AddressRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Street1'
        /// </summary>
        [Fact]
        public void Street1Test()
        {
            // TODO unit test for the property 'Street1'
        }
        /// <summary>
        /// Test the property 'Street2'
        /// </summary>
        [Fact]
        public void Street2Test()
        {
            // TODO unit test for the property 'Street2'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'AddressType'
        /// </summary>
        [Fact]
        public void AddressTypeTest()
        {
            // TODO unit test for the property 'AddressType'
        }
        /// <summary>
        /// Test the property 'IntegrationParams'
        /// </summary>
        [Fact]
        public void IntegrationParamsTest()
        {
            // TODO unit test for the property 'IntegrationParams'
        }
        /// <summary>
        /// Test the property 'LinkedAccountParams'
        /// </summary>
        [Fact]
        public void LinkedAccountParamsTest()
        {
            // TODO unit test for the property 'LinkedAccountParams'
        }

    }

}
