/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing Association
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssociationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Association
        //private Association instance;

        public AssociationTests()
        {
            // TODO uncomment below to create an instance of Association
            //instance = new Association();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Association
        /// </summary>
        [Fact]
        public void AssociationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Association
            //Assert.IsType<Association>(instance);
        }


        /// <summary>
        /// Test the property 'SourceObject'
        /// </summary>
        [Fact]
        public void SourceObjectTest()
        {
            // TODO unit test for the property 'SourceObject'
        }
        /// <summary>
        /// Test the property 'TargetObject'
        /// </summary>
        [Fact]
        public void TargetObjectTest()
        {
            // TODO unit test for the property 'TargetObject'
        }
        /// <summary>
        /// Test the property 'AssociationType'
        /// </summary>
        [Fact]
        public void AssociationTypeTest()
        {
            // TODO unit test for the property 'AssociationType'
        }

    }

}
