/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing AssociationSubType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssociationSubTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssociationSubType
        //private AssociationSubType instance;

        public AssociationSubTypeTests()
        {
            // TODO uncomment below to create an instance of AssociationSubType
            //instance = new AssociationSubType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssociationSubType
        /// </summary>
        [Fact]
        public void AssociationSubTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssociationSubType
            //Assert.IsType<AssociationSubType>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OriginType'
        /// </summary>
        [Fact]
        public void OriginTypeTest()
        {
            // TODO unit test for the property 'OriginType'
        }
        /// <summary>
        /// Test the property 'ModifiedAt'
        /// </summary>
        [Fact]
        public void ModifiedAtTest()
        {
            // TODO unit test for the property 'ModifiedAt'
        }

    }

}
