/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing CommonModelScopeData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonModelScopeDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonModelScopeData
        //private CommonModelScopeData instance;

        public CommonModelScopeDataTests()
        {
            // TODO uncomment below to create an instance of CommonModelScopeData
            //instance = new CommonModelScopeData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonModelScopeData
        /// </summary>
        [Fact]
        public void CommonModelScopeDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonModelScopeData
            //Assert.IsType<CommonModelScopeData>(instance);
        }


        /// <summary>
        /// Test the property 'CommonModels'
        /// </summary>
        [Fact]
        public void CommonModelsTest()
        {
            // TODO unit test for the property 'CommonModels'
        }
        /// <summary>
        /// Test the property 'LinkedAccountId'
        /// </summary>
        [Fact]
        public void LinkedAccountIdTest()
        {
            // TODO unit test for the property 'LinkedAccountId'
        }

    }

}
