/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing CommonModelScopes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonModelScopesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonModelScopes
        //private CommonModelScopes instance;

        public CommonModelScopesTests()
        {
            // TODO uncomment below to create an instance of CommonModelScopes
            //instance = new CommonModelScopes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonModelScopes
        /// </summary>
        [Fact]
        public void CommonModelScopesInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonModelScopes
            //Assert.IsType<CommonModelScopes>(instance);
        }


        /// <summary>
        /// Test the property 'OrganizationLevelScopes'
        /// </summary>
        [Fact]
        public void OrganizationLevelScopesTest()
        {
            // TODO unit test for the property 'OrganizationLevelScopes'
        }
        /// <summary>
        /// Test the property 'ScopeOverrides'
        /// </summary>
        [Fact]
        public void ScopeOverridesTest()
        {
            // TODO unit test for the property 'ScopeOverrides'
        }

    }

}
