/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing CommonModelScopesPostInnerDeserializerRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommonModelScopesPostInnerDeserializerRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CommonModelScopesPostInnerDeserializerRequest
        //private CommonModelScopesPostInnerDeserializerRequest instance;

        public CommonModelScopesPostInnerDeserializerRequestTests()
        {
            // TODO uncomment below to create an instance of CommonModelScopesPostInnerDeserializerRequest
            //instance = new CommonModelScopesPostInnerDeserializerRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CommonModelScopesPostInnerDeserializerRequest
        /// </summary>
        [Fact]
        public void CommonModelScopesPostInnerDeserializerRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CommonModelScopesPostInnerDeserializerRequest
            //Assert.IsType<CommonModelScopesPostInnerDeserializerRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Fact]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }
        /// <summary>
        /// Test the property 'EnabledActions'
        /// </summary>
        [Fact]
        public void EnabledActionsTest()
        {
            // TODO unit test for the property 'EnabledActions'
        }
        /// <summary>
        /// Test the property 'DisabledFields'
        /// </summary>
        [Fact]
        public void DisabledFieldsTest()
        {
            // TODO unit test for the property 'DisabledFields'
        }

    }

}
