/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing Contact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Contact
        //private Contact instance;

        public ContactTests()
        {
            // TODO uncomment below to create an instance of Contact
            //instance = new Contact();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Contact
        /// </summary>
        [Fact]
        public void ContactInstanceTest()
        {
            // TODO uncomment below to test "IsType" Contact
            //Assert.IsType<Contact>(instance);
        }


        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Fact]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }
        /// <summary>
        /// Test the property 'EmailAddresses'
        /// </summary>
        [Fact]
        public void EmailAddressesTest()
        {
            // TODO unit test for the property 'EmailAddresses'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
        /// <summary>
        /// Test the property 'LastActivityAt'
        /// </summary>
        [Fact]
        public void LastActivityAtTest()
        {
            // TODO unit test for the property 'LastActivityAt'
        }
        /// <summary>
        /// Test the property 'RemoteCreatedAt'
        /// </summary>
        [Fact]
        public void RemoteCreatedAtTest()
        {
            // TODO unit test for the property 'RemoteCreatedAt'
        }
        /// <summary>
        /// Test the property 'RemoteWasDeleted'
        /// </summary>
        [Fact]
        public void RemoteWasDeletedTest()
        {
            // TODO unit test for the property 'RemoteWasDeleted'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'FieldMappings'
        /// </summary>
        [Fact]
        public void FieldMappingsTest()
        {
            // TODO unit test for the property 'FieldMappings'
        }
        /// <summary>
        /// Test the property 'ModifiedAt'
        /// </summary>
        [Fact]
        public void ModifiedAtTest()
        {
            // TODO unit test for the property 'ModifiedAt'
        }
        /// <summary>
        /// Test the property 'RemoteData'
        /// </summary>
        [Fact]
        public void RemoteDataTest()
        {
            // TODO unit test for the property 'RemoteData'
        }
        /// <summary>
        /// Test the property 'RemoteFields'
        /// </summary>
        [Fact]
        public void RemoteFieldsTest()
        {
            // TODO unit test for the property 'RemoteFields'
        }

    }

}
