/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing CRMContactResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CRMContactResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CRMContactResponse
        //private CRMContactResponse instance;

        public CRMContactResponseTests()
        {
            // TODO uncomment below to create an instance of CRMContactResponse
            //instance = new CRMContactResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CRMContactResponse
        /// </summary>
        [Fact]
        public void CRMContactResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CRMContactResponse
            //Assert.IsType<CRMContactResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }
        /// <summary>
        /// Test the property 'Warnings'
        /// </summary>
        [Fact]
        public void WarningsTest()
        {
            // TODO unit test for the property 'Warnings'
        }
        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

    }

}
