/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing EmailAddressRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmailAddressRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmailAddressRequest
        //private EmailAddressRequest instance;

        public EmailAddressRequestTests()
        {
            // TODO uncomment below to create an instance of EmailAddressRequest
            //instance = new EmailAddressRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmailAddressRequest
        /// </summary>
        [Fact]
        public void EmailAddressRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmailAddressRequest
            //Assert.IsType<EmailAddressRequest>(instance);
        }


        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Fact]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'EmailAddressType'
        /// </summary>
        [Fact]
        public void EmailAddressTypeTest()
        {
            // TODO unit test for the property 'EmailAddressType'
        }
        /// <summary>
        /// Test the property 'IntegrationParams'
        /// </summary>
        [Fact]
        public void IntegrationParamsTest()
        {
            // TODO unit test for the property 'IntegrationParams'
        }
        /// <summary>
        /// Test the property 'LinkedAccountParams'
        /// </summary>
        [Fact]
        public void LinkedAccountParamsTest()
        {
            // TODO unit test for the property 'LinkedAccountParams'
        }

    }

}
