/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing Lead
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Lead
        //private Lead instance;

        public LeadTests()
        {
            // TODO uncomment below to create an instance of Lead
            //instance = new Lead();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Lead
        /// </summary>
        [Fact]
        public void LeadInstanceTest()
        {
            // TODO uncomment below to test "IsType" Lead
            //Assert.IsType<Lead>(instance);
        }


        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'LeadSource'
        /// </summary>
        [Fact]
        public void LeadSourceTest()
        {
            // TODO unit test for the property 'LeadSource'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Addresses'
        /// </summary>
        [Fact]
        public void AddressesTest()
        {
            // TODO unit test for the property 'Addresses'
        }
        /// <summary>
        /// Test the property 'EmailAddresses'
        /// </summary>
        [Fact]
        public void EmailAddressesTest()
        {
            // TODO unit test for the property 'EmailAddresses'
        }
        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
        /// <summary>
        /// Test the property 'RemoteUpdatedAt'
        /// </summary>
        [Fact]
        public void RemoteUpdatedAtTest()
        {
            // TODO unit test for the property 'RemoteUpdatedAt'
        }
        /// <summary>
        /// Test the property 'RemoteCreatedAt'
        /// </summary>
        [Fact]
        public void RemoteCreatedAtTest()
        {
            // TODO unit test for the property 'RemoteCreatedAt'
        }
        /// <summary>
        /// Test the property 'ConvertedDate'
        /// </summary>
        [Fact]
        public void ConvertedDateTest()
        {
            // TODO unit test for the property 'ConvertedDate'
        }
        /// <summary>
        /// Test the property 'ConvertedContact'
        /// </summary>
        [Fact]
        public void ConvertedContactTest()
        {
            // TODO unit test for the property 'ConvertedContact'
        }
        /// <summary>
        /// Test the property 'ConvertedAccount'
        /// </summary>
        [Fact]
        public void ConvertedAccountTest()
        {
            // TODO unit test for the property 'ConvertedAccount'
        }
        /// <summary>
        /// Test the property 'RemoteWasDeleted'
        /// </summary>
        [Fact]
        public void RemoteWasDeletedTest()
        {
            // TODO unit test for the property 'RemoteWasDeleted'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'FieldMappings'
        /// </summary>
        [Fact]
        public void FieldMappingsTest()
        {
            // TODO unit test for the property 'FieldMappings'
        }
        /// <summary>
        /// Test the property 'RemoteData'
        /// </summary>
        [Fact]
        public void RemoteDataTest()
        {
            // TODO unit test for the property 'RemoteData'
        }
        /// <summary>
        /// Test the property 'RemoteFields'
        /// </summary>
        [Fact]
        public void RemoteFieldsTest()
        {
            // TODO unit test for the property 'RemoteFields'
        }

    }

}
