/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing LeadRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeadRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeadRequest
        //private LeadRequest instance;

        public LeadRequestTests()
        {
            // TODO uncomment below to create an instance of LeadRequest
            //instance = new LeadRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeadRequest
        /// </summary>
        [Fact]
        public void LeadRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LeadRequest
            //Assert.IsType<LeadRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'LeadSource'
        /// </summary>
        [Fact]
        public void LeadSourceTest()
        {
            // TODO unit test for the property 'LeadSource'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'ConvertedDate'
        /// </summary>
        [Fact]
        public void ConvertedDateTest()
        {
            // TODO unit test for the property 'ConvertedDate'
        }
        /// <summary>
        /// Test the property 'ConvertedContact'
        /// </summary>
        [Fact]
        public void ConvertedContactTest()
        {
            // TODO unit test for the property 'ConvertedContact'
        }
        /// <summary>
        /// Test the property 'ConvertedAccount'
        /// </summary>
        [Fact]
        public void ConvertedAccountTest()
        {
            // TODO unit test for the property 'ConvertedAccount'
        }
        /// <summary>
        /// Test the property 'IntegrationParams'
        /// </summary>
        [Fact]
        public void IntegrationParamsTest()
        {
            // TODO unit test for the property 'IntegrationParams'
        }
        /// <summary>
        /// Test the property 'LinkedAccountParams'
        /// </summary>
        [Fact]
        public void LinkedAccountParamsTest()
        {
            // TODO unit test for the property 'LinkedAccountParams'
        }

    }

}
