/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing Note
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NoteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Note
        //private Note instance;

        public NoteTests()
        {
            // TODO uncomment below to create an instance of Note
            //instance = new Note();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Note
        /// </summary>
        [Fact]
        public void NoteInstanceTest()
        {
            // TODO uncomment below to test "IsType" Note
            //Assert.IsType<Note>(instance);
        }


        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Fact]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'Opportunity'
        /// </summary>
        [Fact]
        public void OpportunityTest()
        {
            // TODO unit test for the property 'Opportunity'
        }
        /// <summary>
        /// Test the property 'RemoteUpdatedAt'
        /// </summary>
        [Fact]
        public void RemoteUpdatedAtTest()
        {
            // TODO unit test for the property 'RemoteUpdatedAt'
        }
        /// <summary>
        /// Test the property 'RemoteCreatedAt'
        /// </summary>
        [Fact]
        public void RemoteCreatedAtTest()
        {
            // TODO unit test for the property 'RemoteCreatedAt'
        }
        /// <summary>
        /// Test the property 'RemoteWasDeleted'
        /// </summary>
        [Fact]
        public void RemoteWasDeletedTest()
        {
            // TODO unit test for the property 'RemoteWasDeleted'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'RemoteId'
        /// </summary>
        [Fact]
        public void RemoteIdTest()
        {
            // TODO unit test for the property 'RemoteId'
        }
        /// <summary>
        /// Test the property 'FieldMappings'
        /// </summary>
        [Fact]
        public void FieldMappingsTest()
        {
            // TODO unit test for the property 'FieldMappings'
        }
        /// <summary>
        /// Test the property 'RemoteData'
        /// </summary>
        [Fact]
        public void RemoteDataTest()
        {
            // TODO unit test for the property 'RemoteData'
        }
        /// <summary>
        /// Test the property 'RemoteFields'
        /// </summary>
        [Fact]
        public void RemoteFieldsTest()
        {
            // TODO unit test for the property 'RemoteFields'
        }

    }

}
