/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing ObjectClassDescriptionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObjectClassDescriptionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObjectClassDescriptionRequest
        //private ObjectClassDescriptionRequest instance;

        public ObjectClassDescriptionRequestTests()
        {
            // TODO uncomment below to create an instance of ObjectClassDescriptionRequest
            //instance = new ObjectClassDescriptionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObjectClassDescriptionRequest
        /// </summary>
        [Fact]
        public void ObjectClassDescriptionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObjectClassDescriptionRequest
            //Assert.IsType<ObjectClassDescriptionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'OriginType'
        /// </summary>
        [Fact]
        public void OriginTypeTest()
        {
            // TODO unit test for the property 'OriginType'
        }

    }

}
