/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaginatedOpportunityList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginatedOpportunityListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginatedOpportunityList
        //private PaginatedOpportunityList instance;

        public PaginatedOpportunityListTests()
        {
            // TODO uncomment below to create an instance of PaginatedOpportunityList
            //instance = new PaginatedOpportunityList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginatedOpportunityList
        /// </summary>
        [Fact]
        public void PaginatedOpportunityListInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginatedOpportunityList
            //Assert.IsType<PaginatedOpportunityList>(instance);
        }


        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Fact]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
