/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing PatchedCRMCustomObjectEndpointRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchedCRMCustomObjectEndpointRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchedCRMCustomObjectEndpointRequest
        //private PatchedCRMCustomObjectEndpointRequest instance;

        public PatchedCRMCustomObjectEndpointRequestTests()
        {
            // TODO uncomment below to create an instance of PatchedCRMCustomObjectEndpointRequest
            //instance = new PatchedCRMCustomObjectEndpointRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchedCRMCustomObjectEndpointRequest
        /// </summary>
        [Fact]
        public void PatchedCRMCustomObjectEndpointRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchedCRMCustomObjectEndpointRequest
            //Assert.IsType<PatchedCRMCustomObjectEndpointRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

    }

}
