/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing PatchedEngagementEndpointRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchedEngagementEndpointRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchedEngagementEndpointRequest
        //private PatchedEngagementEndpointRequest instance;

        public PatchedEngagementEndpointRequestTests()
        {
            // TODO uncomment below to create an instance of PatchedEngagementEndpointRequest
            //instance = new PatchedEngagementEndpointRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchedEngagementEndpointRequest
        /// </summary>
        [Fact]
        public void PatchedEngagementEndpointRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchedEngagementEndpointRequest
            //Assert.IsType<PatchedEngagementEndpointRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

    }

}
