/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing PatchedAccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchedAccountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchedAccountRequest
        //private PatchedAccountRequest instance;

        public PatchedAccountRequestTests()
        {
            // TODO uncomment below to create an instance of PatchedAccountRequest
            //instance = new PatchedAccountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchedAccountRequest
        /// </summary>
        [Fact]
        public void PatchedAccountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchedAccountRequest
            //Assert.IsType<PatchedAccountRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Industry'
        /// </summary>
        [Fact]
        public void IndustryTest()
        {
            // TODO unit test for the property 'Industry'
        }
        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
        /// <summary>
        /// Test the property 'NumberOfEmployees'
        /// </summary>
        [Fact]
        public void NumberOfEmployeesTest()
        {
            // TODO unit test for the property 'NumberOfEmployees'
        }
        /// <summary>
        /// Test the property 'LastActivityAt'
        /// </summary>
        [Fact]
        public void LastActivityAtTest()
        {
            // TODO unit test for the property 'LastActivityAt'
        }
        /// <summary>
        /// Test the property 'IntegrationParams'
        /// </summary>
        [Fact]
        public void IntegrationParamsTest()
        {
            // TODO unit test for the property 'IntegrationParams'
        }
        /// <summary>
        /// Test the property 'LinkedAccountParams'
        /// </summary>
        [Fact]
        public void LinkedAccountParamsTest()
        {
            // TODO unit test for the property 'LinkedAccountParams'
        }

    }

}
