/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing RemoteField
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemoteFieldTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemoteField
        //private RemoteField instance;

        public RemoteFieldTests()
        {
            // TODO uncomment below to create an instance of RemoteField
            //instance = new RemoteField();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemoteField
        /// </summary>
        [Fact]
        public void RemoteFieldInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemoteField
            //Assert.IsType<RemoteField>(instance);
        }


        /// <summary>
        /// Test the property 'RemoteFieldClass'
        /// </summary>
        [Fact]
        public void RemoteFieldClassTest()
        {
            // TODO unit test for the property 'RemoteFieldClass'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
