/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing RemoteFieldClass
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemoteFieldClassTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RemoteFieldClass
        //private RemoteFieldClass instance;

        public RemoteFieldClassTests()
        {
            // TODO uncomment below to create an instance of RemoteFieldClass
            //instance = new RemoteFieldClass();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RemoteFieldClass
        /// </summary>
        [Fact]
        public void RemoteFieldClassInstanceTest()
        {
            // TODO uncomment below to test "IsType" RemoteFieldClass
            //Assert.IsType<RemoteFieldClass>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Fact]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'RemoteKeyName'
        /// </summary>
        [Fact]
        public void RemoteKeyNameTest()
        {
            // TODO unit test for the property 'RemoteKeyName'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsCustom'
        /// </summary>
        [Fact]
        public void IsCustomTest()
        {
            // TODO unit test for the property 'IsCustom'
        }
        /// <summary>
        /// Test the property 'IsRequired'
        /// </summary>
        [Fact]
        public void IsRequiredTest()
        {
            // TODO unit test for the property 'IsRequired'
        }
        /// <summary>
        /// Test the property 'FieldType'
        /// </summary>
        [Fact]
        public void FieldTypeTest()
        {
            // TODO unit test for the property 'FieldType'
        }
        /// <summary>
        /// Test the property 'FieldFormat'
        /// </summary>
        [Fact]
        public void FieldFormatTest()
        {
            // TODO unit test for the property 'FieldFormat'
        }
        /// <summary>
        /// Test the property 'FieldChoices'
        /// </summary>
        [Fact]
        public void FieldChoicesTest()
        {
            // TODO unit test for the property 'FieldChoices'
        }
        /// <summary>
        /// Test the property 'ItemSchema'
        /// </summary>
        [Fact]
        public void ItemSchemaTest()
        {
            // TODO unit test for the property 'ItemSchema'
        }

    }

}
