/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing RequestFormatEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestFormatEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestFormatEnum
        //private RequestFormatEnum instance;

        public RequestFormatEnumTests()
        {
            // TODO uncomment below to create an instance of RequestFormatEnum
            //instance = new RequestFormatEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestFormatEnum
        /// </summary>
        [Fact]
        public void RequestFormatEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestFormatEnum
            //Assert.IsType<RequestFormatEnum>(instance);
        }



    }

}
