/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Merge.CRMClient.Api;
using Merge.CRMClient.Model;
using Merge.CRMClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Merge.CRMClient.Test.Model
{
    /// <summary>
    ///  Class for testing TaskRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TaskRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TaskRequest
        //private TaskRequest instance;

        public TaskRequestTests()
        {
            // TODO uncomment below to create an instance of TaskRequest
            //instance = new TaskRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaskRequest
        /// </summary>
        [Fact]
        public void TaskRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TaskRequest
            //Assert.IsType<TaskRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }
        /// <summary>
        /// Test the property 'Account'
        /// </summary>
        [Fact]
        public void AccountTest()
        {
            // TODO unit test for the property 'Account'
        }
        /// <summary>
        /// Test the property 'CompletedDate'
        /// </summary>
        [Fact]
        public void CompletedDateTest()
        {
            // TODO unit test for the property 'CompletedDate'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'IntegrationParams'
        /// </summary>
        [Fact]
        public void IntegrationParamsTest()
        {
            // TODO unit test for the property 'IntegrationParams'
        }
        /// <summary>
        /// Test the property 'LinkedAccountParams'
        /// </summary>
        [Fact]
        public void LinkedAccountParamsTest()
        {
            // TODO unit test for the property 'LinkedAccountParams'
        }
        /// <summary>
        /// Test the property 'RemoteFields'
        /// </summary>
        [Fact]
        public void RemoteFieldsTest()
        {
            // TODO unit test for the property 'RemoteFields'
        }

    }

}
