/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Merge.CRMClient.Client;
using Merge.CRMClient.Model;

namespace Merge.CRMClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAssociationTypesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <returns>CRMAssociationTypeResponse</returns>
        CRMAssociationTypeResponse CustomObjectClassesAssociationTypesCreate(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <returns>ApiResponse of CRMAssociationTypeResponse</returns>
        ApiResponse<CRMAssociationTypeResponse> CustomObjectClassesAssociationTypesCreateWithHttpInfo(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a list of &#x60;AssociationType&#x60; objects.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <returns>PaginatedAssociationTypeList</returns>
        PaginatedAssociationTypeList CustomObjectClassesAssociationTypesList(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a list of &#x60;AssociationType&#x60; objects.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <returns>ApiResponse of PaginatedAssociationTypeList</returns>
        ApiResponse<PaginatedAssociationTypeList> CustomObjectClassesAssociationTypesListWithHttpInfo(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <returns>MetaResponse</returns>
        MetaResponse CustomObjectClassesAssociationTypesMetaPostRetrieve(string xAccountToken, Guid customObjectClassId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <returns>ApiResponse of MetaResponse</returns>
        ApiResponse<MetaResponse> CustomObjectClassesAssociationTypesMetaPostRetrieveWithHttpInfo(string xAccountToken, Guid customObjectClassId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <returns>AssociationType</returns>
        AssociationType CustomObjectClassesAssociationTypesRetrieve(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <returns>ApiResponse of AssociationType</returns>
        ApiResponse<AssociationType> CustomObjectClassesAssociationTypesRetrieveWithHttpInfo(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAssociationTypesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CRMAssociationTypeResponse</returns>
        System.Threading.Tasks.Task<CRMAssociationTypeResponse> CustomObjectClassesAssociationTypesCreateAsync(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CRMAssociationTypeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CRMAssociationTypeResponse>> CustomObjectClassesAssociationTypesCreateWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a list of &#x60;AssociationType&#x60; objects.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaginatedAssociationTypeList</returns>
        System.Threading.Tasks.Task<PaginatedAssociationTypeList> CustomObjectClassesAssociationTypesListAsync(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns a list of &#x60;AssociationType&#x60; objects.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaginatedAssociationTypeList)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaginatedAssociationTypeList>> CustomObjectClassesAssociationTypesListWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MetaResponse</returns>
        System.Threading.Tasks.Task<MetaResponse> CustomObjectClassesAssociationTypesMetaPostRetrieveAsync(string xAccountToken, Guid customObjectClassId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MetaResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<MetaResponse>> CustomObjectClassesAssociationTypesMetaPostRetrieveWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssociationType</returns>
        System.Threading.Tasks.Task<AssociationType> CustomObjectClassesAssociationTypesRetrieveAsync(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </remarks>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssociationType)</returns>
        System.Threading.Tasks.Task<ApiResponse<AssociationType>> CustomObjectClassesAssociationTypesRetrieveWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAssociationTypesApi : IAssociationTypesApiSync, IAssociationTypesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AssociationTypesApi : IAssociationTypesApi
    {
        private Merge.CRMClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AssociationTypesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AssociationTypesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssociationTypesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AssociationTypesApi(String basePath)
        {
            this.Configuration = Merge.CRMClient.Client.Configuration.MergeConfigurations(
                Merge.CRMClient.Client.GlobalConfiguration.Instance,
                new Merge.CRMClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Merge.CRMClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Merge.CRMClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Merge.CRMClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssociationTypesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AssociationTypesApi(Merge.CRMClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Merge.CRMClient.Client.Configuration.MergeConfigurations(
                Merge.CRMClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Merge.CRMClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Merge.CRMClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Merge.CRMClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AssociationTypesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AssociationTypesApi(Merge.CRMClient.Client.ISynchronousClient client, Merge.CRMClient.Client.IAsynchronousClient asyncClient, Merge.CRMClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Merge.CRMClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Merge.CRMClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Merge.CRMClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Merge.CRMClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Merge.CRMClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <returns>CRMAssociationTypeResponse</returns>
        public CRMAssociationTypeResponse CustomObjectClassesAssociationTypesCreate(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?))
        {
            Merge.CRMClient.Client.ApiResponse<CRMAssociationTypeResponse> localVarResponse = CustomObjectClassesAssociationTypesCreateWithHttpInfo(xAccountToken, customObjectClassId, cRMAssociationTypeEndpointRequest, isDebugMode, runAsync);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <returns>ApiResponse of CRMAssociationTypeResponse</returns>
        public Merge.CRMClient.Client.ApiResponse<CRMAssociationTypeResponse> CustomObjectClassesAssociationTypesCreateWithHttpInfo(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesCreate");

            // verify the required parameter 'cRMAssociationTypeEndpointRequest' is set
            if (cRMAssociationTypeEndpointRequest == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'cRMAssociationTypeEndpointRequest' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesCreate");

            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json",
                "application/x-www-form-urlencoded",
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            if (isDebugMode != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "is_debug_mode", isDebugMode));
            }
            if (runAsync != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "run_async", runAsync));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter
            localVarRequestOptions.Data = cRMAssociationTypeEndpointRequest;

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CRMAssociationTypeResponse>("/custom-object-classes/{custom_object_class_id}/association-types", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CRMAssociationTypeResponse</returns>
        public async System.Threading.Tasks.Task<CRMAssociationTypeResponse> CustomObjectClassesAssociationTypesCreateAsync(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Merge.CRMClient.Client.ApiResponse<CRMAssociationTypeResponse> localVarResponse = await CustomObjectClassesAssociationTypesCreateWithHttpInfoAsync(xAccountToken, customObjectClassId, cRMAssociationTypeEndpointRequest, isDebugMode, runAsync, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Creates an &#x60;AssociationType&#x60; object with the given values.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cRMAssociationTypeEndpointRequest"></param>
        /// <param name="isDebugMode">Whether to include debug fields (such as log file links) in the response. (optional)</param>
        /// <param name="runAsync">Whether or not third-party updates should be run asynchronously. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CRMAssociationTypeResponse)</returns>
        public async System.Threading.Tasks.Task<Merge.CRMClient.Client.ApiResponse<CRMAssociationTypeResponse>> CustomObjectClassesAssociationTypesCreateWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, CRMAssociationTypeEndpointRequest cRMAssociationTypeEndpointRequest, bool? isDebugMode = default(bool?), bool? runAsync = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesCreate");

            // verify the required parameter 'cRMAssociationTypeEndpointRequest' is set
            if (cRMAssociationTypeEndpointRequest == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'cRMAssociationTypeEndpointRequest' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesCreate");


            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json", 
                "application/x-www-form-urlencoded", 
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            if (isDebugMode != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "is_debug_mode", isDebugMode));
            }
            if (runAsync != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "run_async", runAsync));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter
            localVarRequestOptions.Data = cRMAssociationTypeEndpointRequest;

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CRMAssociationTypeResponse>("/custom-object-classes/{custom_object_class_id}/association-types", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesCreate", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns a list of &#x60;AssociationType&#x60; objects.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <returns>PaginatedAssociationTypeList</returns>
        public PaginatedAssociationTypeList CustomObjectClassesAssociationTypesList(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string))
        {
            Merge.CRMClient.Client.ApiResponse<PaginatedAssociationTypeList> localVarResponse = CustomObjectClassesAssociationTypesListWithHttpInfo(xAccountToken, customObjectClassId, createdAfter, createdBefore, cursor, includeDeletedData, includeRemoteData, modifiedAfter, modifiedBefore, pageSize, remoteId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns a list of &#x60;AssociationType&#x60; objects.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <returns>ApiResponse of PaginatedAssociationTypeList</returns>
        public Merge.CRMClient.Client.ApiResponse<PaginatedAssociationTypeList> CustomObjectClassesAssociationTypesListWithHttpInfo(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesList");

            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            if (createdAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "created_after", createdAfter));
            }
            if (createdBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "created_before", createdBefore));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (includeDeletedData != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "include_deleted_data", includeDeletedData));
            }
            if (includeRemoteData != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "include_remote_data", includeRemoteData));
            }
            if (modifiedAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "modified_after", modifiedAfter));
            }
            if (modifiedBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "modified_before", modifiedBefore));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (remoteId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "remote_id", remoteId));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PaginatedAssociationTypeList>("/custom-object-classes/{custom_object_class_id}/association-types", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns a list of &#x60;AssociationType&#x60; objects.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaginatedAssociationTypeList</returns>
        public async System.Threading.Tasks.Task<PaginatedAssociationTypeList> CustomObjectClassesAssociationTypesListAsync(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Merge.CRMClient.Client.ApiResponse<PaginatedAssociationTypeList> localVarResponse = await CustomObjectClassesAssociationTypesListWithHttpInfoAsync(xAccountToken, customObjectClassId, createdAfter, createdBefore, cursor, includeDeletedData, includeRemoteData, modifiedAfter, modifiedBefore, pageSize, remoteId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns a list of &#x60;AssociationType&#x60; objects.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="createdAfter">If provided, will only return objects created after this datetime. (optional)</param>
        /// <param name="createdBefore">If provided, will only return objects created before this datetime. (optional)</param>
        /// <param name="cursor">The pagination cursor value. (optional)</param>
        /// <param name="includeDeletedData">Whether to include data that was marked as deleted by third party webhooks. (optional)</param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="modifiedAfter">If provided, only objects synced by Merge after this date time will be returned. (optional)</param>
        /// <param name="modifiedBefore">If provided, only objects synced by Merge before this date time will be returned. (optional)</param>
        /// <param name="pageSize">Number of results to return per page. (optional)</param>
        /// <param name="remoteId">The API provider&#39;s ID for the given object. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaginatedAssociationTypeList)</returns>
        public async System.Threading.Tasks.Task<Merge.CRMClient.Client.ApiResponse<PaginatedAssociationTypeList>> CustomObjectClassesAssociationTypesListWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, DateTime? createdAfter = default(DateTime?), DateTime? createdBefore = default(DateTime?), string cursor = default(string), bool? includeDeletedData = default(bool?), bool? includeRemoteData = default(bool?), DateTime? modifiedAfter = default(DateTime?), DateTime? modifiedBefore = default(DateTime?), int? pageSize = default(int?), string remoteId = default(string), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesList");


            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            if (createdAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "created_after", createdAfter));
            }
            if (createdBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "created_before", createdBefore));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (includeDeletedData != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "include_deleted_data", includeDeletedData));
            }
            if (includeRemoteData != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "include_remote_data", includeRemoteData));
            }
            if (modifiedAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "modified_after", modifiedAfter));
            }
            if (modifiedBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "modified_before", modifiedBefore));
            }
            if (pageSize != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "page_size", pageSize));
            }
            if (remoteId != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "remote_id", remoteId));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<PaginatedAssociationTypeList>("/custom-object-classes/{custom_object_class_id}/association-types", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesList", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <returns>MetaResponse</returns>
        public MetaResponse CustomObjectClassesAssociationTypesMetaPostRetrieve(string xAccountToken, Guid customObjectClassId)
        {
            Merge.CRMClient.Client.ApiResponse<MetaResponse> localVarResponse = CustomObjectClassesAssociationTypesMetaPostRetrieveWithHttpInfo(xAccountToken, customObjectClassId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <returns>ApiResponse of MetaResponse</returns>
        public Merge.CRMClient.Client.ApiResponse<MetaResponse> CustomObjectClassesAssociationTypesMetaPostRetrieveWithHttpInfo(string xAccountToken, Guid customObjectClassId)
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesMetaPostRetrieve");

            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<MetaResponse>("/custom-object-classes/{custom_object_class_id}/association-types/meta/post", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesMetaPostRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of MetaResponse</returns>
        public async System.Threading.Tasks.Task<MetaResponse> CustomObjectClassesAssociationTypesMetaPostRetrieveAsync(string xAccountToken, Guid customObjectClassId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Merge.CRMClient.Client.ApiResponse<MetaResponse> localVarResponse = await CustomObjectClassesAssociationTypesMetaPostRetrieveWithHttpInfoAsync(xAccountToken, customObjectClassId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns metadata for &#x60;CRMAssociationType&#x60; POSTs.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (MetaResponse)</returns>
        public async System.Threading.Tasks.Task<Merge.CRMClient.Client.ApiResponse<MetaResponse>> CustomObjectClassesAssociationTypesMetaPostRetrieveWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesMetaPostRetrieve");


            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<MetaResponse>("/custom-object-classes/{custom_object_class_id}/association-types/meta/post", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesMetaPostRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <returns>AssociationType</returns>
        public AssociationType CustomObjectClassesAssociationTypesRetrieve(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?))
        {
            Merge.CRMClient.Client.ApiResponse<AssociationType> localVarResponse = CustomObjectClassesAssociationTypesRetrieveWithHttpInfo(xAccountToken, customObjectClassId, id, includeRemoteData);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <returns>ApiResponse of AssociationType</returns>
        public Merge.CRMClient.Client.ApiResponse<AssociationType> CustomObjectClassesAssociationTypesRetrieveWithHttpInfo(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesRetrieve");

            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Merge.CRMClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (includeRemoteData != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "include_remote_data", includeRemoteData));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AssociationType>("/custom-object-classes/{custom_object_class_id}/association-types/{id}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssociationType</returns>
        public async System.Threading.Tasks.Task<AssociationType> CustomObjectClassesAssociationTypesRetrieveAsync(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Merge.CRMClient.Client.ApiResponse<AssociationType> localVarResponse = await CustomObjectClassesAssociationTypesRetrieveWithHttpInfoAsync(xAccountToken, customObjectClassId, id, includeRemoteData, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Returns an &#x60;AssociationType&#x60; object with the given &#x60;id&#x60;.
        /// </summary>
        /// <exception cref="Merge.CRMClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xAccountToken">Token identifying the end user.</param>
        /// <param name="customObjectClassId"></param>
        /// <param name="id"></param>
        /// <param name="includeRemoteData">Whether to include the original data Merge fetched from the third-party to produce these models. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssociationType)</returns>
        public async System.Threading.Tasks.Task<Merge.CRMClient.Client.ApiResponse<AssociationType>> CustomObjectClassesAssociationTypesRetrieveWithHttpInfoAsync(string xAccountToken, Guid customObjectClassId, Guid id, bool? includeRemoteData = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'xAccountToken' is set
            if (xAccountToken == null)
                throw new Merge.CRMClient.Client.ApiException(400, "Missing required parameter 'xAccountToken' when calling AssociationTypesApi->CustomObjectClassesAssociationTypesRetrieve");


            Merge.CRMClient.Client.RequestOptions localVarRequestOptions = new Merge.CRMClient.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Merge.CRMClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Merge.CRMClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("custom_object_class_id", Merge.CRMClient.Client.ClientUtils.ParameterToString(customObjectClassId)); // path parameter
            localVarRequestOptions.PathParameters.Add("id", Merge.CRMClient.Client.ClientUtils.ParameterToString(id)); // path parameter
            if (includeRemoteData != null)
            {
                localVarRequestOptions.QueryParameters.Add(Merge.CRMClient.Client.ClientUtils.ParameterToMultiMap("", "include_remote_data", includeRemoteData));
            }
            localVarRequestOptions.HeaderParameters.Add("X-Account-Token", Merge.CRMClient.Client.ClientUtils.ParameterToString(xAccountToken)); // header parameter

            // authentication (tokenAuth) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<AssociationType>("/custom-object-classes/{custom_object_class_id}/association-types/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CustomObjectClassesAssociationTypesRetrieve", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
