/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.CRMClient.Client.OpenAPIDateConverter;

namespace Merge.CRMClient.Model
{
    /// <summary>
    /// Defines CardinalityEnum
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CardinalityEnum
    {
        /// <summary>
        /// Enum ONETOONE for value: ONE_TO_ONE
        /// </summary>
        [EnumMember(Value = "ONE_TO_ONE")]
        ONETOONE = 1,

        /// <summary>
        /// Enum MANYTOONE for value: MANY_TO_ONE
        /// </summary>
        [EnumMember(Value = "MANY_TO_ONE")]
        MANYTOONE = 2,

        /// <summary>
        /// Enum MANYTOMANY for value: MANY_TO_MANY
        /// </summary>
        [EnumMember(Value = "MANY_TO_MANY")]
        MANYTOMANY = 3,

        /// <summary>
        /// Enum ONETOMANY for value: ONE_TO_MANY
        /// </summary>
        [EnumMember(Value = "ONE_TO_MANY")]
        ONETOMANY = 4

    }

}
