/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.CRMClient.Client.OpenAPIDateConverter;

namespace Merge.CRMClient.Model
{
    /// <summary>
    /// * &#x60;string&#x60; - string * &#x60;number&#x60; - number * &#x60;date&#x60; - date * &#x60;datetime&#x60; - datetime * &#x60;bool&#x60; - bool * &#x60;list&#x60; - list
    /// </summary>
    /// <value>* &#x60;string&#x60; - string * &#x60;number&#x60; - number * &#x60;date&#x60; - date * &#x60;datetime&#x60; - datetime * &#x60;bool&#x60; - bool * &#x60;list&#x60; - list</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FieldTypeEnum
    {
        /// <summary>
        /// Enum String for value: string
        /// </summary>
        [EnumMember(Value = "string")]
        String = 1,

        /// <summary>
        /// Enum Number for value: number
        /// </summary>
        [EnumMember(Value = "number")]
        Number = 2,

        /// <summary>
        /// Enum Date for value: date
        /// </summary>
        [EnumMember(Value = "date")]
        Date = 3,

        /// <summary>
        /// Enum Datetime for value: datetime
        /// </summary>
        [EnumMember(Value = "datetime")]
        Datetime = 4,

        /// <summary>
        /// Enum Bool for value: bool
        /// </summary>
        [EnumMember(Value = "bool")]
        Bool = 5,

        /// <summary>
        /// Enum List for value: list
        /// </summary>
        [EnumMember(Value = "list")]
        List = 6

    }

}
