/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.CRMClient.Client.OpenAPIDateConverter;

namespace Merge.CRMClient.Model
{
    /// <summary>
    /// # The Lead Object ### Description The &#x60;Lead&#x60; object is used to represent an individual who is a potential customer. ### Usage Example TODO
    /// </summary>
    [DataContract(Name = "LeadRequest")]
    public partial class LeadRequest : IEquatable<LeadRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeadRequest" /> class.
        /// </summary>
        /// <param name="owner">The lead&#39;s owner..</param>
        /// <param name="leadSource">The lead&#39;s source..</param>
        /// <param name="title">The lead&#39;s title..</param>
        /// <param name="company">The lead&#39;s company..</param>
        /// <param name="firstName">The lead&#39;s first name..</param>
        /// <param name="lastName">The lead&#39;s last name..</param>
        /// <param name="addresses">addresses.</param>
        /// <param name="emailAddresses">emailAddresses.</param>
        /// <param name="phoneNumbers">phoneNumbers.</param>
        /// <param name="convertedDate">When the lead was converted..</param>
        /// <param name="convertedContact">The contact of the converted lead..</param>
        /// <param name="convertedAccount">The account of the converted lead..</param>
        /// <param name="integrationParams">integrationParams.</param>
        /// <param name="linkedAccountParams">linkedAccountParams.</param>
        /// <param name="remoteFields">remoteFields.</param>
        public LeadRequest(Guid? owner = default(Guid?), string leadSource = default(string), string title = default(string), string company = default(string), string firstName = default(string), string lastName = default(string), List<AddressRequest> addresses = default(List<AddressRequest>), List<EmailAddressRequest> emailAddresses = default(List<EmailAddressRequest>), List<PhoneNumberRequest> phoneNumbers = default(List<PhoneNumberRequest>), DateTime? convertedDate = default(DateTime?), Guid? convertedContact = default(Guid?), Guid? convertedAccount = default(Guid?), Dictionary<string, Object> integrationParams = default(Dictionary<string, Object>), Dictionary<string, Object> linkedAccountParams = default(Dictionary<string, Object>), List<RemoteFieldRequest> remoteFields = default(List<RemoteFieldRequest>))
        {
            this.Owner = owner;
            this.LeadSource = leadSource;
            this.Title = title;
            this.Company = company;
            this.FirstName = firstName;
            this.LastName = lastName;
            this.Addresses = addresses;
            this.EmailAddresses = emailAddresses;
            this.PhoneNumbers = phoneNumbers;
            this.ConvertedDate = convertedDate;
            this.ConvertedContact = convertedContact;
            this.ConvertedAccount = convertedAccount;
            this.IntegrationParams = integrationParams;
            this.LinkedAccountParams = linkedAccountParams;
            this.RemoteFields = remoteFields;
        }

        /// <summary>
        /// The lead&#39;s owner.
        /// </summary>
        /// <value>The lead&#39;s owner.</value>
        [DataMember(Name = "owner", EmitDefaultValue = true)]
        public Guid? Owner { get; set; }

        /// <summary>
        /// The lead&#39;s source.
        /// </summary>
        /// <value>The lead&#39;s source.</value>
        [DataMember(Name = "lead_source", EmitDefaultValue = true)]
        public string LeadSource { get; set; }

        /// <summary>
        /// The lead&#39;s title.
        /// </summary>
        /// <value>The lead&#39;s title.</value>
        [DataMember(Name = "title", EmitDefaultValue = true)]
        public string Title { get; set; }

        /// <summary>
        /// The lead&#39;s company.
        /// </summary>
        /// <value>The lead&#39;s company.</value>
        [DataMember(Name = "company", EmitDefaultValue = true)]
        public string Company { get; set; }

        /// <summary>
        /// The lead&#39;s first name.
        /// </summary>
        /// <value>The lead&#39;s first name.</value>
        [DataMember(Name = "first_name", EmitDefaultValue = true)]
        public string FirstName { get; set; }

        /// <summary>
        /// The lead&#39;s last name.
        /// </summary>
        /// <value>The lead&#39;s last name.</value>
        [DataMember(Name = "last_name", EmitDefaultValue = true)]
        public string LastName { get; set; }

        /// <summary>
        /// Gets or Sets Addresses
        /// </summary>
        [DataMember(Name = "addresses", EmitDefaultValue = false)]
        public List<AddressRequest> Addresses { get; set; }

        /// <summary>
        /// Gets or Sets EmailAddresses
        /// </summary>
        [DataMember(Name = "email_addresses", EmitDefaultValue = false)]
        public List<EmailAddressRequest> EmailAddresses { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumbers
        /// </summary>
        [DataMember(Name = "phone_numbers", EmitDefaultValue = false)]
        public List<PhoneNumberRequest> PhoneNumbers { get; set; }

        /// <summary>
        /// When the lead was converted.
        /// </summary>
        /// <value>When the lead was converted.</value>
        [DataMember(Name = "converted_date", EmitDefaultValue = true)]
        public DateTime? ConvertedDate { get; set; }

        /// <summary>
        /// The contact of the converted lead.
        /// </summary>
        /// <value>The contact of the converted lead.</value>
        [DataMember(Name = "converted_contact", EmitDefaultValue = true)]
        public Guid? ConvertedContact { get; set; }

        /// <summary>
        /// The account of the converted lead.
        /// </summary>
        /// <value>The account of the converted lead.</value>
        [DataMember(Name = "converted_account", EmitDefaultValue = true)]
        public Guid? ConvertedAccount { get; set; }

        /// <summary>
        /// Gets or Sets IntegrationParams
        /// </summary>
        [DataMember(Name = "integration_params", EmitDefaultValue = true)]
        public Dictionary<string, Object> IntegrationParams { get; set; }

        /// <summary>
        /// Gets or Sets LinkedAccountParams
        /// </summary>
        [DataMember(Name = "linked_account_params", EmitDefaultValue = true)]
        public Dictionary<string, Object> LinkedAccountParams { get; set; }

        /// <summary>
        /// Gets or Sets RemoteFields
        /// </summary>
        [DataMember(Name = "remote_fields", EmitDefaultValue = false)]
        public List<RemoteFieldRequest> RemoteFields { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LeadRequest {\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  LeadSource: ").Append(LeadSource).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  LastName: ").Append(LastName).Append("\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  EmailAddresses: ").Append(EmailAddresses).Append("\n");
            sb.Append("  PhoneNumbers: ").Append(PhoneNumbers).Append("\n");
            sb.Append("  ConvertedDate: ").Append(ConvertedDate).Append("\n");
            sb.Append("  ConvertedContact: ").Append(ConvertedContact).Append("\n");
            sb.Append("  ConvertedAccount: ").Append(ConvertedAccount).Append("\n");
            sb.Append("  IntegrationParams: ").Append(IntegrationParams).Append("\n");
            sb.Append("  LinkedAccountParams: ").Append(LinkedAccountParams).Append("\n");
            sb.Append("  RemoteFields: ").Append(RemoteFields).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LeadRequest);
        }

        /// <summary>
        /// Returns true if LeadRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of LeadRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LeadRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Owner == input.Owner ||
                    (this.Owner != null &&
                    this.Owner.Equals(input.Owner))
                ) && 
                (
                    this.LeadSource == input.LeadSource ||
                    (this.LeadSource != null &&
                    this.LeadSource.Equals(input.LeadSource))
                ) && 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.Company == input.Company ||
                    (this.Company != null &&
                    this.Company.Equals(input.Company))
                ) && 
                (
                    this.FirstName == input.FirstName ||
                    (this.FirstName != null &&
                    this.FirstName.Equals(input.FirstName))
                ) && 
                (
                    this.LastName == input.LastName ||
                    (this.LastName != null &&
                    this.LastName.Equals(input.LastName))
                ) && 
                (
                    this.Addresses == input.Addresses ||
                    this.Addresses != null &&
                    input.Addresses != null &&
                    this.Addresses.SequenceEqual(input.Addresses)
                ) && 
                (
                    this.EmailAddresses == input.EmailAddresses ||
                    this.EmailAddresses != null &&
                    input.EmailAddresses != null &&
                    this.EmailAddresses.SequenceEqual(input.EmailAddresses)
                ) && 
                (
                    this.PhoneNumbers == input.PhoneNumbers ||
                    this.PhoneNumbers != null &&
                    input.PhoneNumbers != null &&
                    this.PhoneNumbers.SequenceEqual(input.PhoneNumbers)
                ) && 
                (
                    this.ConvertedDate == input.ConvertedDate ||
                    (this.ConvertedDate != null &&
                    this.ConvertedDate.Equals(input.ConvertedDate))
                ) && 
                (
                    this.ConvertedContact == input.ConvertedContact ||
                    (this.ConvertedContact != null &&
                    this.ConvertedContact.Equals(input.ConvertedContact))
                ) && 
                (
                    this.ConvertedAccount == input.ConvertedAccount ||
                    (this.ConvertedAccount != null &&
                    this.ConvertedAccount.Equals(input.ConvertedAccount))
                ) && 
                (
                    this.IntegrationParams == input.IntegrationParams ||
                    this.IntegrationParams != null &&
                    input.IntegrationParams != null &&
                    this.IntegrationParams.SequenceEqual(input.IntegrationParams)
                ) && 
                (
                    this.LinkedAccountParams == input.LinkedAccountParams ||
                    this.LinkedAccountParams != null &&
                    input.LinkedAccountParams != null &&
                    this.LinkedAccountParams.SequenceEqual(input.LinkedAccountParams)
                ) && 
                (
                    this.RemoteFields == input.RemoteFields ||
                    this.RemoteFields != null &&
                    input.RemoteFields != null &&
                    this.RemoteFields.SequenceEqual(input.RemoteFields)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Owner != null)
                    hashCode = hashCode * 59 + this.Owner.GetHashCode();
                if (this.LeadSource != null)
                    hashCode = hashCode * 59 + this.LeadSource.GetHashCode();
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.Company != null)
                    hashCode = hashCode * 59 + this.Company.GetHashCode();
                if (this.FirstName != null)
                    hashCode = hashCode * 59 + this.FirstName.GetHashCode();
                if (this.LastName != null)
                    hashCode = hashCode * 59 + this.LastName.GetHashCode();
                if (this.Addresses != null)
                    hashCode = hashCode * 59 + this.Addresses.GetHashCode();
                if (this.EmailAddresses != null)
                    hashCode = hashCode * 59 + this.EmailAddresses.GetHashCode();
                if (this.PhoneNumbers != null)
                    hashCode = hashCode * 59 + this.PhoneNumbers.GetHashCode();
                if (this.ConvertedDate != null)
                    hashCode = hashCode * 59 + this.ConvertedDate.GetHashCode();
                if (this.ConvertedContact != null)
                    hashCode = hashCode * 59 + this.ConvertedContact.GetHashCode();
                if (this.ConvertedAccount != null)
                    hashCode = hashCode * 59 + this.ConvertedAccount.GetHashCode();
                if (this.IntegrationParams != null)
                    hashCode = hashCode * 59 + this.IntegrationParams.GetHashCode();
                if (this.LinkedAccountParams != null)
                    hashCode = hashCode * 59 + this.LinkedAccountParams.GetHashCode();
                if (this.RemoteFields != null)
                    hashCode = hashCode * 59 + this.RemoteFields.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
