/*
 * Merge CRM API
 *
 * The unified API for building rich integrations with multiple CRM platforms.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: hello@merge.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Merge.CRMClient.Client.OpenAPIDateConverter;

namespace Merge.CRMClient.Model
{
    /// <summary>
    /// RemoteFieldRequest
    /// </summary>
    [DataContract(Name = "RemoteFieldRequest")]
    public partial class RemoteFieldRequest : IEquatable<RemoteFieldRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoteFieldRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RemoteFieldRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoteFieldRequest" /> class.
        /// </summary>
        /// <param name="remoteFieldClass">remoteFieldClass (required).</param>
        /// <param name="value">value.</param>
        public RemoteFieldRequest(Guid remoteFieldClass = default(Guid), Dictionary<string, Object> value = default(Dictionary<string, Object>))
        {
            this.RemoteFieldClass = remoteFieldClass;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets RemoteFieldClass
        /// </summary>
        [DataMember(Name = "remote_field_class", IsRequired = true, EmitDefaultValue = false)]
        public Guid RemoteFieldClass { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public Dictionary<string, Object> Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RemoteFieldRequest {\n");
            sb.Append("  RemoteFieldClass: ").Append(RemoteFieldClass).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RemoteFieldRequest);
        }

        /// <summary>
        /// Returns true if RemoteFieldRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of RemoteFieldRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RemoteFieldRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RemoteFieldClass == input.RemoteFieldClass ||
                    (this.RemoteFieldClass != null &&
                    this.RemoteFieldClass.Equals(input.RemoteFieldClass))
                ) && 
                (
                    this.Value == input.Value ||
                    this.Value != null &&
                    input.Value != null &&
                    this.Value.SequenceEqual(input.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RemoteFieldClass != null)
                    hashCode = hashCode * 59 + this.RemoteFieldClass.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
